name: Package Test

on:
  pull_request:
    types: [ synchronize, opened ]
      
jobs:
  package:
    name: Test
    runs-on: windows-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v4
    - name: Install Poppler
      shell: bash -l {0}
      run: |
        POPPLER_VERSION="$(sed -n 's/^POPPLER_VERSION=//p' package.sh | tr -d '\r')"
        conda install -c conda-forge liblzma expat "poppler=$POPPLER_VERSION" -y
    - name: Run Package Script
      shell: bash -l {0}
      run: ./package.sh
      env:
        PKGS_PATH_DIR: /c/Users/runneradmin/conda_pkgs_dir

    - name: Test Package
      shell: pwsh
      run: .\test-package.ps1 -PackageRoot "${{ github.workspace }}\poppler-${{ env.POPPLER_VERSION }}"

    - name: Zip Release
      run: Compress-Archive "${{ github.workspace }}\poppler-${{ env.POPPLER_VERSION }}" Release-${{ env.POPPLER_VERSION }}-${{ env.BUILD }}.zip
      shell: pwsh
    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: Poppler-${{ env.POPPLER_VERSION }}-${{ env.BUILD }}
        path: ${{ github.workspace }}\Release-${{ env.POPPLER_VERSION }}-${{ env.BUILD }}.zip
